:: Copyright (c) Microsoft Corporation
:: SPDX-License-Identifier: MIT

clang -g -O2 -target bpf -mcpu=v1 -std=gnu89 -nostdinc -D__NR_CPUS__=10 -Wextra -Werror -Wshadow -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-gnu-variable-sized-type-not-at-end -Wdeclaration-after-statement -DSECLABEL=2 -DNODE_MAC={.addr={0x0,0x15,0x5d,0x6e,0x85,0x4}} -DCALLS_MAP=cilium_calls_xdp -Dcapture_enabled=0 -DDISABLE_LOOPBACK_LB -I.\ -I..\..\external\cilium\bpf -I..\..\external\cilium\bpf\include -I..\ -I..\..\include -I..\..\libs\platform\kernel -c ..\..\external\cilium\bpf\bpf_xdp.c -o ..\object\bpf_xdp_dsr.o -DEBPF_FOR_WINDOWS -DMODE_DSR

clang -g -O2 -target bpf -mcpu=v1 -std=gnu89 -nostdinc -D__NR_CPUS__=10 -Wextra -Werror -Wshadow -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-gnu-variable-sized-type-not-at-end -Wdeclaration-after-statement -DSECLABEL=2 -DNODE_MAC={.addr={0x0,0x15,0x5d,0x6e,0x85,0x4}} -DCALLS_MAP=cilium_calls_xdp -Dcapture_enabled=0 -DDISABLE_LOOPBACK_LB -I.\ -I..\..\external\cilium\bpf -I..\..\external\cilium\bpf\include -I..\ -I..\..\include -I..\..\libs\platform\kernel -c ..\..\external\cilium\bpf\bpf_xdp.c -o ..\object\bpf_xdp_snat.o -DEBPF_FOR_WINDOWS -DMODE_SNAT

@rem clang -g -O2 -target bpf -mcpu=v1 -std=gnu89 -nostdinc -D__NR_CPUS__=10 -Wall -Wextra -Werror -Wshadow -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-gnu-variable-sized-type-not-at-end -Wdeclaration-after-statement -DSECLABEL=2 -DNODE_MAC={.addr={0x0,0x15,0x5d,0x6e,0x85,0x4}} -DCALLS_MAP=cilium_calls_xdp -Dcapture_enabled=0 -DDISABLE_LOOPBACK_LB -I.\include -I. -I..\ -I..\..\include -I..\..\libs\platform\kernel -c bpf_xdp.c -o ..\object\bpf_xdp_dsr_debug.o -DEBPF_FOR_WINDOWS -DMODE_DSR -DTRACK_CODE_FLOW

@rem clang -g -O2 -target bpf -mcpu=v1 -std=gnu89 -nostdinc -D__NR_CPUS__=10 -Wall -Wextra -Werror -Wshadow -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-gnu-variable-sized-type-not-at-end -Wdeclaration-after-statement -DSECLABEL=2 -DNODE_MAC={.addr={0x0,0x15,0x5d,0x6e,0x85,0x4}} -DCALLS_MAP=cilium_calls_xdp -Dcapture_enabled=0 -DDISABLE_LOOPBACK_LB -I.\include -I. -I..\ -I..\..\include -I..\..\libs\platform\kernel -c bpf_xdp.c -o ..\object\bpf_xdp_snat_debug.o -DEBPF_FOR_WINDOWS -DMODE_SNAT -DTRACK_CODE_FLOW
