#define CONNTRACK 1
#define CONNTRACK_ACCOUNTING 1
#undef CONNTRACK_LOCAL
#undef DEBUG
#undef LB_DEBUG
#define DROP_NOTIFY 1
#undef MONITOR_AGGREGATION
#undef POLICY_AUDIT_MODE
#define POLICY_VERDICT_NOTIFY 1
#define TRACE_NOTIFY 1
